export const  GETALL_USERDETAILE_REQUEST = 'GETALL_USERDETAILE_REQUEST';
export const  GETALL_USERDETAILE_SUCCESS = 'GETALL_USERDETAILE_SUCCESS';
export const  GETALL_USERDETAILE_FAILURE = 'GETALL_USERDETAILE_FAILURE';
