export const  GETALL_USERDETAILE_REQUEST = 'GETALL_USERDETAILE_REQUEST';
export const  GETALL_USERDETAILE_SUCCESS = 'GETALL_USERDETAILE_SUCCESS';
export const  GETALL_USERDETAILE_FAILURE = 'GETALL_USERDETAILE_FAILURE';


export const  GET_SIGNUP_DETAILS_REQUEST = 'GET_SIGNUP_DETAILS_REQUEST';
export const  GET_SIGNUP_DETAILS_SUCCESS = 'GET_SIGNUP_DETAILS_SUCCESS';
export const  GET_SIGNUP_DETAILS_FAILURE = 'GET_SIGNUP_DETAILS_FAILURE';

